# -*- coding: utf-8 -*-
"""Cópia de DiffusionUI_Beta -> TPU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QI6nAngL9-IcEtzkpidqEFCqG7Be7BO

# Célula 1: Conexão com o Cofre (Google Drive)
Esta célula conecta o seu Colab ao Drive e garante que toda a estrutura de pastas (Modelos_Base, LoRAs, VAEs, Text_Encoders e Imagens_Geradas) exista, para não perdermos nenhum arquivo.
"""

from google.colab import drive
import os

print("📂 ETAPA 1: CONECTANDO AO GOOGLE DRIVE")
print("--------------------------------------------------")
drive.mount('/content/drive')

base_path = '/content/drive/MyDrive/Stable_Diffusion_Dados'
pastas = ['Modelos_Base', 'LoRAs', 'VAEs', 'Text_Encoders', 'Imagens_Geradas']

for pasta in pastas:
    caminho_completo = os.path.join(base_path, pasta)
    os.makedirs(caminho_completo, exist_ok=True)

print("✅ Pastas verificadas e sincronizadas com sucesso!")

"""# Célula 2: O Radar de Hardware (Cérebro do Sistema)
Esta célula lê a placa mãe virtual do Colab e define se você está usando a A100 (luxo), a L4 (custo-benefício), a T4 (economia) ou apenas a CPU, ajustando a potência do motor.

"""

import torch
import os
import multiprocessing

print("🧠 ETAPA 2: DETECÇÃO DE HARDWARE E OTIMIZAÇÃO (NOVA ARQUITETURA)")
print("--------------------------------------------------")

hardware_type = "UNKNOWN"
args_otimizados = ""
cores = multiprocessing.cpu_count()

if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)
    print(f"✅ GPU NVIDIA Detectada: {gpu_name}")

    if any(x in gpu_name for x in ["H100", "A100"]):
        hardware_type = "GPU_LUXO"
        args_otimizados = "--theme dark --cuda-malloc --cuda-stream"
    elif "L4" in gpu_name:
        hardware_type = "GPU_MEDIA"
        args_otimizados = "--theme dark"
    else:
        hardware_type = "GPU_ECONOMICA"
        args_otimizados = "--theme dark --always-offload-from-vram"
else:
    hardware_type = "CPU_TURBO"
    os.environ['OMP_NUM_THREADS'] = str(cores)
    args_otimizados = "--theme dark --use-cpu all --skip-torch-cuda-test --no-half --precision full"

os.environ['FORGE_ARGS'] = args_otimizados
os.environ['HARDWARE_TYPE'] = hardware_type
print(f"⚙‣ Modo: {hardware_type} | Args: {args_otimizados}")

"""# Célula 3: Instalação do Forge e Construção das Pontes
Baixa o WebUI Forge e cria os "buracos de minhoca" (symlinks) para que a IA leia e salve tudo direto no seu Google Drive, sem lotar a memória temporária do Colab.


"""

import os

print("⚙️ ETAPA 3: INSTALANDO FORGE E CONSTRUINDO PONTES")
print("--------------------------------------------------")

!git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git

forge_models = '/content/stable-diffusion-webui-forge/models'
forge_outputs = '/content/stable-diffusion-webui-forge/output'

# Limpa o lixo padrão
!rm -rf {forge_models}/Stable-diffusion {forge_models}/Lora {forge_models}/VAE {forge_outputs}

# Conecta ao seu Drive
!ln -s /content/drive/MyDrive/Stable_Diffusion_Dados/Modelos_Base {forge_models}/Stable-diffusion
!ln -s /content/drive/MyDrive/Stable_Diffusion_Dados/LoRAs {forge_models}/Lora
!ln -s /content/drive/MyDrive/Stable_Diffusion_Dados/VAEs {forge_models}/VAE
!mkdir -p {forge_models}/text_encoder
!ln -s /content/drive/MyDrive/Stable_Diffusion_Dados/Text_Encoders/* {forge_models}/text_encoder/ 2>/dev/null || true
!ln -s /content/drive/MyDrive/Stable_Diffusion_Dados/Imagens_Geradas {forge_outputs}

print("✅ Infraestrutura montada com sucesso!")

"""# Célula 4: Aplicação de Vacinas e Dependências Extra
Aquela nossa célula mágica que arranca pacotes conflitantes (como o Numpy e o Skimage) e instala o essencial para o ReActor funcionar perfeitamente.
"""

print("💉 ETAPA 4: APLICAÇÃO DE VACINAS E DEPENDÊNCIAS")
print("--------------------------------------------------")

print("➤ Corrigindo interpretadores de texto (CLIP)...")
!python3.10 -m pip install -q ftfy regex tqdm
!python3.10 -m pip install -q https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip --no-build-isolation

print("➤ Erradicando erro de C-Header (Numpy Size Changed)...")
!python3.10 -m pip uninstall -y scikit-image numpy scipy
!python3.10 -m pip install "numpy<2.0.0" "scikit-image<0.23.0" "scipy<1.13.0"

print("➤ Instalando dependências de mapeamento facial (ReActor)...")
!python3.10 -m pip install -q joblib insightface

print("✅ Sistema esterilizado e preparado!")

"""# Célula 5: A Central de Downloads e Arquivos
O seu gerenciador com API Key do Civitai.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import subprocess
import time
from google.colab import files

pasta_base = '/content/drive/MyDrive/Stable_Diffusion_Dados'
pasta_modelos, pasta_loras, pasta_vaes, pasta_text_encoders = f"{pasta_base}/Modelos_Base", f"{pasta_base}/LoRAs", f"{pasta_base}/VAEs", f"{pasta_base}/Text_Encoders"
caixa_api_key = widgets.Password(description='API Key:', placeholder='Cole sua chave do Civitai (Opcional)', layout=widgets.Layout(width='400px'))
api_box = widgets.HBox([caixa_api_key])

# ==========================================
# ABA 1: DOWNLOADER (INTERNET)
# ==========================================
lista_arquivos = widgets.VBox([])
def criar_linha_download():
    tipo = widgets.Dropdown(options=['Model / Checkpoint', 'LoRA', 'VAE', 'Text Encoder'], value='Model / Checkpoint', layout=widgets.Layout(width='180px'))
    link = widgets.Text(placeholder='Cole o link do download', layout=widgets.Layout(width='300px'))
    nome = widgets.Text(placeholder='ex: modelo.safetensors', layout=widgets.Layout(width='200px'))
    btn_remover = widgets.Button(description='❌', button_style='danger', layout=widgets.Layout(width='40px'))
    linha = widgets.HBox([tipo, link, nome, btn_remover])
    def remover(b): lista_arquivos.children = [c for c in lista_arquivos.children if c != linha]
    btn_remover.on_click(remover)
    return linha

lista_arquivos.children = [criar_linha_download()]
btn_adicionar = widgets.Button(description='➕ Adicionar Arquivo', button_style='info', layout=widgets.Layout(width='200px'))
btn_baixar = widgets.Button(description='⬇️ Baixar Tudo Agora', button_style='success', layout=widgets.Layout(width='200px'))
saida_log = widgets.Output()

def adicionar_linha(b): lista_arquivos.children = list(lista_arquivos.children) + [criar_linha_download()]
btn_adicionar.on_click(adicionar_linha)

def iniciar_download(b):
    with saida_log:
        clear_output()
        print("🚀 Iniciando processamento da fila...\n")
        chave_api = caixa_api_key.value.strip()
        for linha in lista_arquivos.children:
            tipo, url_original, nome = linha.children[0].value, linha.children[1].value.strip(), linha.children[2].value.strip()
            if not url_original or not nome: continue
            url_final = f"{url_original}{'&' if '?' in url_original else '?'}token={chave_api}" if chave_api and "civitai" in url_original.lower() else url_original

            if tipo == 'Model / Checkpoint': pasta_destino = pasta_modelos
            elif tipo == 'LoRA': pasta_destino = pasta_loras
            elif tipo == 'VAE': pasta_destino = pasta_vaes
            else: pasta_destino = pasta_text_encoders

            caminho_completo = f"{pasta_destino}/{nome}"
            print(f"⏳ Baixando: {nome}...")
            resultado = subprocess.run(['wget', '-q', '--show-progress', '-O', caminho_completo, url_final])
            if resultado.returncode == 0 and os.path.exists(caminho_completo) and os.path.getsize(caminho_completo) > 50000:
                print(f"✅ SUCESSO!\n")
            else:
                print(f"❌ ERRO no download. Verifique o link.\n")
                if os.path.exists(caminho_completo): os.remove(caminho_completo)
        print("🎉 FILA CONCLUÍDA!")
        atualizar_gerenciador()

btn_baixar.on_click(iniciar_download)
box_downloader = widgets.VBox([widgets.HTML("<p>Recomendado para Modelos Pesados (GBs). Velocidade máxima da rede do Google.</p>"), lista_arquivos, widgets.HBox([btn_adicionar, btn_baixar]), saida_log])

# ==========================================
# ABA 2: UPLOAD NATIVO DO COLAB (CORRIGIDO)
# ==========================================
dropdown_destino_upload = widgets.Dropdown(options=['Model / Checkpoint', 'LoRA', 'VAE', 'Text Encoder'], value='LoRA', description='Destino:')
btn_iniciar_upload = widgets.Button(description='🚀 Iniciar Uploader do Google', button_style='success', layout=widgets.Layout(width='250px'))
out_upload = widgets.Output()

def acionar_upload_nativo(b):
    with out_upload:
        clear_output()
        tipo = dropdown_destino_upload.value
        pasta = pasta_modelos if tipo == 'Model / Checkpoint' else pasta_loras if tipo == 'LoRA' else pasta_vaes if tipo == 'VAE' else pasta_text_encoders

        print(f"📡 Conectando ao uploader raiz do Google Colab...")
        print(f"➤ Destino escolhido: Pasta de {tipo}")
        print("👇 Clique no botão 'Escolher arquivos' que apareceu logo abaixo:")

        try:
            arquivos_upados = files.upload()

            if not arquivos_upados:
                print("\n⚠️ Nenhum arquivo foi selecionado. Operação cancelada.")
                return

            print(f"\n🚀 Gravando os arquivos direto no seu Google Drive...")

            # Loop de gravação direta (ignora pastas locais e grava os dados puros)
            for nome_arquivo, conteudo_bytes in arquivos_upados.items():
                caminho_final = os.path.join(pasta, nome_arquivo)

                with open(caminho_final, 'wb') as f:
                    f.write(conteudo_bytes)

                # Apaga o lixo temporário que o Colab deixou na pasta local
                if os.path.exists(nome_arquivo):
                    os.remove(nome_arquivo)

                print(f"   ✅ '{nome_arquivo}' salvo com sucesso!")

            print("\n🎉 Lote concluído!")
            atualizar_gerenciador()

        except Exception as e:
            print(f"\n❌ ERRO FATAL: {e}")

btn_iniciar_upload.on_click(acionar_upload_nativo)
aviso_upload = widgets.HTML("""<div style='background-color: #d4edda; color: #155724; padding: 10px; border-radius: 5px; margin-bottom: 10px;'><b>✅ UPLOADER NATIVO:</b> O arquivo é gravado na memória e injetado diretamente no Drive.</div>""")
box_upload = widgets.VBox([aviso_upload, widgets.HBox([dropdown_destino_upload, btn_iniciar_upload]), out_upload])

# ==========================================
# ABA 3: GERENCIADOR (CRUD)
# ==========================================
out_gerenciador = widgets.Output()
btn_atualizar_lista = widgets.Button(description='🔄 Atualizar Lista', button_style='info')

def listar_arquivos(pasta):
    if not os.path.exists(pasta): return []
    return [{'nome': f, 'caminho': os.path.join(pasta, f), 'tamanho': os.path.getsize(os.path.join(pasta, f)) / (1024 * 1024)} for f in os.listdir(pasta) if os.path.isfile(os.path.join(pasta, f))]

def atualizar_gerenciador(b=None):
    with out_gerenciador:
        clear_output()
        display(widgets.HTML("<p>Seus arquivos atuais no Google Drive:</p>"))
        for titulo, pasta in [("Modelos Base", pasta_modelos), ("LoRAs", pasta_loras), ("VAEs", pasta_vaes), ("Text Encoders", pasta_text_encoders)]:
            display(widgets.HTML(f"<h4>{titulo}</h4>"))
            arquivos = listar_arquivos(pasta)
            if not arquivos:
                display(widgets.HTML("<i>Nenhum arquivo encontrado.</i>"))
                continue
            for arq in arquivos:
                lbl_nome = widgets.Label(f"📄 {arq['nome']} ({arq['tamanho']:.1f} MB)", layout=widgets.Layout(width='320px'))
                txt_link_sub = widgets.Text(placeholder='Cole novo link', layout=widgets.Layout(width='180px'))
                btn_sub = widgets.Button(description='🔄 Substituir', button_style='warning', layout=widgets.Layout(width='100px'))
                btn_del = widgets.Button(description='🗑️ Apagar', button_style='danger', layout=widgets.Layout(width='90px'))
                box_confirmacao = widgets.HBox([])
                linha = widgets.HBox([lbl_nome, txt_link_sub, btn_sub, btn_del, box_confirmacao])

                def criar_evento_apagar(path, box, btn_d, btn_s):
                    def ao_clicar_apagar(b):
                        btn_sim, btn_nao = widgets.Button(description='✅ Confirmar', button_style='success', layout=widgets.Layout(width='100px')), widgets.Button(description='❌ Cancelar', button_style='danger', layout=widgets.Layout(width='90px'))
                        def ao_confirmar(bs): os.remove(path); atualizar_gerenciador()
                        def ao_cancelar(bn): box.children = []; btn_d.disabled = False; btn_s.disabled = False
                        btn_sim.on_click(ao_confirmar); btn_nao.on_click(ao_cancelar)
                        btn_d.disabled, btn_s.disabled = True, True
                        box.children = [widgets.Label("Certeza?"), btn_sim, btn_nao]
                    return ao_clicar_apagar
                btn_del.on_click(criar_evento_apagar(arq['caminho'], box_confirmacao, btn_del, btn_sub))

                def criar_evento_substituir(path, txt, nome):
                    def ao_clicar_substituir(b):
                        url = txt.value.strip()
                        if not url: return
                        with out_gerenciador:
                            clear_output()
                            chave = caixa_api_key.value.strip()
                            url_final = f"{url}{'&' if '?' in url else '?'}token={chave}" if chave and "civitai" in url.lower() else url
                            print("🗑️ 1. Apagando antigo..."); os.remove(path)
                            print("⏳ 2. Baixando novo...")
                            subprocess.run(['wget', '-q', '--show-progress', '-O', path, url_final])
                            time.sleep(2); atualizar_gerenciador()
                    return ao_clicar_substituir
                btn_sub.on_click(criar_evento_substituir(arq['caminho'], txt_link_sub, arq['nome']))
                display(linha)

btn_atualizar_lista.on_click(atualizar_gerenciador)
atualizar_gerenciador()

abas = widgets.Tab(children=[box_downloader, box_upload, widgets.VBox([btn_atualizar_lista, out_gerenciador])])
abas.set_title(0, '📥 Baixar (Internet)')
abas.set_title(1, '📤 Upload (PC Local)')
abas.set_title(2, '📁 Gerenciar Arquivos')
display(widgets.HTML("<h2>🎛️ Central de Modelos</h2>"), api_box, abas)

"""# Célula 5.5: O Cofre de Extensões (Instalação Automática)
Crie uma nova Célula de Código logo acima da sua Célula 6 (A de Ignição) e cole este código. Ele já está configurado com o Civitai Browser+ e o ReActor:
"""

import os

pasta_extensoes = '/content/stable-diffusion-webui-forge/extensions'
extensoes = [
    "https://github.com/BlafKing/sd-civitai-browser-plus",
    "https://github.com/Gourieff/sd-webui-reactor"
]

print("☁‣ ETAPA 4: INSTALAÇÃO DE EXTENSÕES E DEPENDÊNCIAS REQUISITADAS")
print("--------------------------------------------------")

# Garante que o pip existe no Python 3.10 para evitar erros de instalação
if os.system("python3.10 -m pip --version") != 0:
    print("   [⚙] Recuperando PIP para Python 3.10...")
    os.system("curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10")

for url in extensoes:
    nome = url.split('/')[-1]
    caminho = os.path.join(pasta_extensoes, nome)
    if not os.path.exists(caminho):
        print(f"   [⌄] Instalando {nome}...")
        os.system(f"git clone -q {url} {caminho}")

print("   [✅] Ajustando bibliotecas para o ReActor...")
!python3.10 -m pip install -q insightface joblib

print("--------------------------------------------------")
print("✅ Extensões e dependências prontas!")

"""# Célula 6: A Ignição (Boot Adaptativo)
Lê o "manual" criado pela Célula 2 e liga a interface gráfica respeitando as regras do hardware atual.
"""

import os
import subprocess
import multiprocessing
import sys

print("🚀 ETAPA 6: CHECKLIST DE PRÉ-IGNIÇÃO E DIAGNÓSTICO...")
print("="*70)

alertas_nao_fatais = []
erros_fatais = []
ferramentas_ativas = ["WebUI Forge (Core)", "Python 3.10 (Forçado)"]

# ==========================================
# 1. AUTODIAGNÓSTICO E CORREÇÕES DE PACOTES
# ==========================================
print("🔍 1. Verificando integridade das dependências vitais...")

# Verificando PIP no Python 3.10
try:
    subprocess.run(["python3.10", "-m", "pip", "--version"], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    print("   [+] Instalador PIP: OK")
except subprocess.CalledProcessError:
    print("   [!] Instalador PIP corrompido ou ausente. Aplicando autocorreção silenciosa...")
    os.system("curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 > /dev/null 2>&1")
    ferramentas_ativas.append("PIP (Recuperado)")

# Verificando CLIP
try:
    import clip
    print("   [+] Interpretador CLIP: OK")
except ImportError:
    print("   [!] CLIP ausente. Reaplicando ferramentas de compilação...")
    os.system("python3.10 -m pip install -q --upgrade pip setuptools wheel")
    os.system("python3.10 -m pip install -q ftfy regex tqdm")
    os.system("python3.10 -m pip install -q https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip --no-build-isolation")
    ferramentas_ativas.append("OpenAI CLIP (Vacinado)")

# ⚠️ A ORDEM DE RESTRIÇÃO DO PIP (A Solução Definitiva)
print("   [!] Aplicando blindagem matemática com Ordem de Restrição Global (PIP_CONSTRAINT)...")
with open('/content/restricao_pip.txt', 'w') as f:
    f.write("numpy<2.0.0\nscikit-image<0.23.0\nscipy<1.13.0\n")
os.environ["PIP_CONSTRAINT"] = "/content/restricao_pip.txt"

os.system("python3.10 -m pip uninstall -y scikit-image numpy scipy > /dev/null 2>&1")
os.system("python3.10 -m pip install -q \"numpy<2.0.0\" \"scikit-image<0.23.0\" \"scipy<1.13.0\" insightface joblib")
ferramentas_ativas.append("Numpy Clássico (Bloqueado por Restrição)")
ferramentas_ativas.append("Insightface (Ativo)")

# ==========================================
# 2. ANÁLISE DE HARDWARE E AVISOS (BOTTLENECKS)
# ==========================================
hardware = os.environ.get('HARDWARE_TYPE', 'UNKNOWN')
gpu_name = "Nenhuma (Renderização por Processador)"
vram_total = 0

if hardware == "TPU":
    erros_fatais.append("Hardware Incompatível: O Google Colab alocou uma TPU. O Forge exige tecnologia CUDA (Nvidia).")
else:
    try:
        import torch
        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            vram_total = torch.cuda.get_device_properties(0).total_memory / (1024**3)
            ferramentas_ativas.append("PyTorch com Aceleração CUDA")

            if "T4" in gpu_name or "G4" in gpu_name:
                alertas_nao_fatais.append(f"Gargalo de Memória (VRAM): Sua GPU ({gpu_name}) possui apenas {vram_total:.1f}GB. Para usar o modelo FLUX sem travar, baixe EXCLUSIVAMENTE versões compactadas (FP8).")
        else:
            raise ImportError
    except ImportError:
        alertas_nao_fatais.append("Aceleração Gráfica Ausente: Você está rodando no modo CPU. A geração será EXTREMAMENTE LENTA.")

        arquivo_mem = '/content/stable-diffusion-webui-forge/backend/memory_management.py'
        if os.path.exists(arquivo_mem):
            with open(arquivo_mem, 'r') as f: cod = f.read()
            if "DummyProp" not in cod:
                fake_gpu = 'type("DummyProp", (object,), {"total_memory": 32*1024*1024*1024, "major": 8, "minor": 0, "name": "CPU-Hacker-GPU"})()'
                cod = cod.replace("torch.cuda.current_device()", "'cpu'")
                cod = cod.replace("torch.cuda.get_device_properties(device).total_memory", "(32 * 1024 * 1024 * 1024)")
                cod = cod.replace("torch.cuda.get_device_properties(device)", fake_gpu)
                cod = cod.replace('torch.cuda.get_device_properties("cuda")', fake_gpu)
                cod = cod.replace("torch.cuda.mem_get_info(device)", "((32 * 1024 * 1024 * 1024), (32 * 1024 * 1024 * 1024))")
                with open(arquivo_mem, 'w') as f: f.write(cod)

# ==========================================
# 3. RELATÓRIO FINAL DO AMBIENTE
# ==========================================
print("\n" + "="*70)
print("📊 RELATÓRIO DO SISTEMA DO ESTÚDIO")
print("="*70)
print(f"🖥️ Acelerador Gráfico : {gpu_name}")
if vram_total > 0:
    print(f"💾 Memória de Vídeo   : {vram_total:.1f} GB VRAM")
print(f"⚙️ Processador (CPU)  : {multiprocessing.cpu_count()} Núcleos Lógicos alocados")
print(f"🧰 Ferramentas Base   : {', '.join(ferramentas_ativas)}")
print("="*70)

if erros_fatais:
    print("\n❌ ERRO CRÍTICO ENCONTRADO (Ignição Abortada):")
    for erro in erros_fatais:
        print(f"   ► {erro}")
else:
    if alertas_nao_fatais:
        print("\n⚠️ AVISOS DE PERFORMANCE:")
        for aviso in alertas_nao_fatais:
            print(f"   ► {aviso}")

    print("\n🌐 INICIANDO O SERVIDOR...")
    print("   [+] O link público da interface será gerado logo abaixo.")
    print("   [+] Procure pela URL azul terminando em 'gradio.live'. Clique nela para abrir o estúdio!")
    print("-" * 70 + "\n")

    argumentos = os.environ.get('FORGE_ARGS', '--theme dark')
    os.chdir('/content/stable-diffusion-webui-forge')
    os.environ["MPLBACKEND"] = "agg"

    !python3.10 launch.py {argumentos} --share --enable-insecure-extension-access

"""Abaixo, um código melhorado

*   Item da lista

*   Item da lista

*   Item da lista

*   Item da lista

*   Item da lista

*   Item da lista
*   Item da lista


*   Item da lista


*   Item da lista


*   Item da lista


*   Item da lista


*   Item da lista

# Célula 1: A Fundação (Conexão Segura com o Drive)
Esta célula resolve o erro de "Mountpoint must not already contain files" e garante que suas pastas (incluindo a de VAEs) existam. Agora com a pasta Text_Encoders.
"""

from google.colab import drive
import os

print("🔍 ETAPA 1: VERIFICAÇÃO DO GOOGLE DRIVE")
print("--------------------------------------------------")

print("➤ Ação: Conectando ao Google Drive...")
drive.mount('/content/drive', force_remount=True)

print("\n➤ Ação: Verificando a estrutura de pastas permanentes...")
pasta_base = '/content/drive/MyDrive/Stable_Diffusion_Dados'
# Adicionamos a pasta Text_Encoders na lista de verificação/criação
pastas = ['Modelos_Base', 'LoRAs', 'VAEs', 'Text_Encoders', 'Imagens_Geradas']

for p in pastas:
    caminho = f"{pasta_base}/{p}"
    if not os.path.exists(caminho):
        print(f"   [+] Criando pasta ausente: {p}")
        os.makedirs(caminho)
    else:
        print(f"   [✓] Pasta {p} já existe e está segura.")

print("--------------------------------------------------")
print("✅ ETAPA 1 CONCLUÍDA: Seu cofre de arquivos está pronto!")

"""# Célula 2: O Motor (Instalação e Restauração do Forge)
Esta célula detecta se o Colab sofreu um reset, resolve o erro da "pasta fantasma sem o launch.py", instala o Python 3.10 e cria os atalhos.
"""

import os
from IPython.display import clear_output

print("🔍 ETAPA 2: VERIFICAÇÃO DO SISTEMA E WEBUI FORGE")
print("--------------------------------------------------")

print("➤ Ação: Configurando o motor Python 3.10...")
!apt-get update -qq
!apt-get install software-properties-common -y -qq
!add-apt-repository ppa:deadsnakes/ppa -y -qq
!apt-get update -qq
!apt-get install python3.10 python3.10-venv python3.10-dev python3.10-distutils -y -qq
!curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 -q

print("\n➤ Ação: Verificando a integridade do WebUI Forge...")
forge_path = '/content/stable-diffusion-webui-forge'
pasta_base = '/content/drive/MyDrive/Stable_Diffusion_Dados'

if os.path.exists(forge_path):
    if not os.path.exists(f"{forge_path}/launch.py"):
        print("   [!] AVISO: Pasta corrompida detectada! Forçando limpeza...")
        !rm -rf {forge_path}
        !git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git {forge_path}
    else:
        print("   [✓] Forge detectado e intacto.")
else:
    print("   [+] Forge não encontrado. Iniciando download...")
    !git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git {forge_path}

print("\n➤ Ação: Criando as 'Pontes' (Symlinks) entre o Forge e o seu Drive...")
!rm -rf {forge_path}/models/Stable-diffusion && ln -s "{pasta_base}/Modelos_Base" {forge_path}/models/Stable-diffusion
!rm -rf {forge_path}/models/Lora && ln -s "{pasta_base}/LoRAs" {forge_path}/models/Lora
!rm -rf {forge_path}/models/VAE && ln -s "{pasta_base}/VAEs" {forge_path}/models/VAE
# A MÁGICA NOVA: Criando a ponte para a pasta oculta de Text Encoders do Forge
!rm -rf {forge_path}/models/text_encoder && ln -s "{pasta_base}/Text_Encoders" {forge_path}/models/text_encoder
!rm -rf {forge_path}/outputs && ln -s "{pasta_base}/Imagens_Geradas" {forge_path}/outputs

clear_output()
print("✅ ETAPA 2 CONCLUÍDA: Sistema base e atalhos configurados com sucesso!")

"""# Célula 3: O Antídoto (Vacinas contra Atualizações do Colab)
Esta é a barreira de defesa. Ela se antecipa a todos os erros de incompatibilidade matemática e de bibliotecas quebradas que enfrentamos.
"""

import os

print("🔍 ETAPA 3: APLICAÇÃO DE VACINAS E CORREÇÕES (FORCED FIX)")
print("--------------------------------------------------")

# Ordem de Restrição Global para o PIP
with open('/content/constraints.txt', 'w') as f:
    f.write("numpy<2.0.0\nscikit-image<0.23.0\nscipy<1.13.0\n")
os.environ['PIP_CONSTRAINT'] = '/content/constraints.txt'

print("➤ Vacina 1: CLIP e Ferramentas de Build")
!python3.10 -m pip install -q --upgrade pip setuptools wheel
!python3.10 -m pip install -q ftfy regex tqdm
!python3.10 -m pip install -q https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip --no-build-isolation

print("\n➤ Vacina 2: Limpeza e Alinhamento Matemático")
# Removemos sobras de pacotes que exigem Numpy 2.x para evitar conflitos binários
!python3.10 -m pip uninstall -y scikit-image numpy scipy opencv-python opencv-contrib-python opencv-python-headless > /dev/null 2>&1
!python3.10 -m pip install -q "numpy<2.0.0" "scikit-image<0.23.0" "scipy<1.13.0" "opencv-python-headless<4.10"

print("\n➤ Vacina 3: Dependências ReActor")
!python3.10 -m pip install -q joblib insightface

print("--------------------------------------------------")
print("✅ ETAPA 3 CONCLUÍDA: Ambiente blindado com restrição global!")

"""# Célula 4: A Central de Downloads e Arquivos
O seu gerenciador com API Key do Civitai.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import subprocess
import time

pasta_base = '/content/drive/MyDrive/Stable_Diffusion_Dados'
pasta_modelos, pasta_loras, pasta_vaes, pasta_text_encoders = f"{pasta_base}/Modelos_Base", f"{pasta_base}/LoRAs", f"{pasta_base}/VAEs", f"{pasta_base}/Text_Encoders"
caixa_api_key = widgets.Password(description='API Key:', placeholder='Cole sua chave do Civitai aqui(c3aeb29fccd6c6417a7a30b126b91a4d)', layout=widgets.Layout(width='400px'))
api_box = widgets.HBox([caixa_api_key])
lista_arquivos = widgets.VBox([])

def criar_linha_download():
    # Adicionado Text Encoder no Dropdown
    tipo = widgets.Dropdown(options=['Model / Checkpoint', 'LoRA', 'VAE', 'Text Encoder'], value='Model / Checkpoint', layout=widgets.Layout(width='180px'))
    link = widgets.Text(placeholder='Cole o link do download', layout=widgets.Layout(width='300px'))
    nome = widgets.Text(placeholder='ex: modelo.safetensors', layout=widgets.Layout(width='200px'))
    btn_remover = widgets.Button(description='❌', button_style='danger', layout=widgets.Layout(width='40px'))
    linha = widgets.HBox([tipo, link, nome, btn_remover])
    def remover(b): lista_arquivos.children = [c for c in lista_arquivos.children if c != linha]
    btn_remover.on_click(remover)
    return linha

lista_arquivos.children = [criar_linha_download()]
btn_adicionar = widgets.Button(description='➕ Adicionar Arquivo', button_style='info', layout=widgets.Layout(width='200px'))
btn_baixar = widgets.Button(description='⬇️ Baixar Tudo Agora', button_style='success', layout=widgets.Layout(width='200px'))
saida_log = widgets.Output()

def adicionar_linha(b): lista_arquivos.children = list(lista_arquivos.children) + [criar_linha_download()]
btn_adicionar.on_click(adicionar_linha)

def iniciar_download(b):
    with saida_log:
        clear_output()
        print("🚀 Iniciando processamento da fila...\n")
        chave_api = caixa_api_key.value.strip()
        for linha in lista_arquivos.children:
            tipo, url_original, nome = linha.children[0].value, linha.children[1].value.strip(), linha.children[2].value.strip()
            if not url_original or not nome: continue
            url_final = f"{url_original}{'&' if '?' in url_original else '?'}token={chave_api}" if chave_api else url_original

            # Roteamento inteligente de pastas
            if tipo == 'Model / Checkpoint': pasta_destino = pasta_modelos
            elif tipo == 'LoRA': pasta_destino = pasta_loras
            elif tipo == 'VAE': pasta_destino = pasta_vaes
            else: pasta_destino = pasta_text_encoders

            caminho_completo = f"{pasta_destino}/{nome}"
            print(f"⏳ Baixando: {nome}...")
            resultado = subprocess.run(['wget', '-q', '--show-progress', '-O', caminho_completo, url_final])
            if resultado.returncode == 0 and os.path.exists(caminho_completo) and os.path.getsize(caminho_completo) > 50000:
                print(f"✅ SUCESSO!\n")
            else:
                print(f"❌ ERRO. Link quebrado ou sem permissão. Arquivo apagado.\n")
                if os.path.exists(caminho_completo): os.remove(caminho_completo)
        print("🎉 FILA CONCLUÍDA!")
        atualizar_gerenciador()

btn_baixar.on_click(iniciar_download)
box_downloader = widgets.VBox([widgets.HTML("<p>Adicione links para salvar novos arquivos diretamente no Drive:</p>"), lista_arquivos, widgets.HBox([btn_adicionar, btn_baixar]), saida_log])
out_gerenciador = widgets.Output()

def listar_arquivos(pasta):
    if not os.path.exists(pasta): return []
    return [{'nome': f, 'caminho': os.path.join(pasta, f), 'tamanho': os.path.getsize(os.path.join(pasta, f)) / (1024 * 1024)} for f in os.listdir(pasta) if os.path.isfile(os.path.join(pasta, f))]

def atualizar_gerenciador():
    with out_gerenciador:
        clear_output()
        display(widgets.HTML("<p>Visualize, substitua ou apague arquivos que já estão salvos no seu espaço:</p>"))

        # Loop atualizado para ler, atualizar e deletar os Text Encoders
        for titulo, pasta in [("Modelos Base (Checkpoints)", pasta_modelos), ("LoRAs", pasta_loras), ("VAEs", pasta_vaes), ("Text Encoders", pasta_text_encoders)]:
            display(widgets.HTML(f"<h4>{titulo}</h4>"))
            arquivos = listar_arquivos(pasta)
            if not arquivos:
                display(widgets.HTML("<i>Nenhum arquivo encontrado.</i>"))
                continue
            for arq in arquivos:
                lbl_nome = widgets.Label(f"📄 {arq['nome']} ({arq['tamanho']:.1f} MB)", layout=widgets.Layout(width='320px'))
                txt_link_sub = widgets.Text(placeholder='Cole o novo link aqui', layout=widgets.Layout(width='180px'))
                btn_sub = widgets.Button(description='🔄 Substituir', button_style='warning', layout=widgets.Layout(width='100px'))
                btn_del = widgets.Button(description='🗑️ Apagar', button_style='danger', layout=widgets.Layout(width='90px'))
                box_confirmacao = widgets.HBox([])
                linha = widgets.HBox([lbl_nome, txt_link_sub, btn_sub, btn_del, box_confirmacao])

                def criar_evento_apagar(path, box, btn_d, btn_s):
                    def ao_clicar_apagar(b):
                        btn_sim, btn_nao = widgets.Button(description='✅ Confirmar', button_style='success', layout=widgets.Layout(width='100px')), widgets.Button(description='❌ Cancelar', button_style='danger', layout=widgets.Layout(width='90px'))
                        def ao_confirmar(bs): os.remove(path); atualizar_gerenciador()
                        def ao_cancelar(bn): box.children = []; btn_d.disabled = False; btn_s.disabled = False
                        btn_sim.on_click(ao_confirmar); btn_nao.on_click(ao_cancelar)
                        btn_d.disabled, btn_s.disabled = True, True
                        box.children = [widgets.Label("Tem certeza?"), btn_sim, btn_nao]
                    return ao_clicar_apagar
                btn_del.on_click(criar_evento_apagar(arq['caminho'], box_confirmacao, btn_del, btn_sub))

                def criar_evento_substituir(path, txt, nome):
                    def ao_clicar_substituir(b):
                        url = txt.value.strip()
                        if not url: txt.placeholder = "⚠️ Cole um link primeiro!"; return
                        with out_gerenciador:
                            clear_output()
                            print(f"🔄 Iniciando a substituição de '{nome}'...\n")
                            chave = caixa_api_key.value.strip()
                            url_final = f"{url}{'&' if '?' in url else '?'}token={chave}" if chave else url
                            print("🗑️ 1. Apagando a versão antiga..."); os.remove(path)
                            print("⏳ 2. Baixando a nova versão...")
                            resultado = subprocess.run(['wget', '-q', '--show-progress', '-O', path, url_final])
                            if resultado.returncode == 0 and os.path.exists(path) and os.path.getsize(path) > 50000: print("\n✅ Substituição concluída com perfeição!")
                            else: print("\n❌ Erro no download.")
                            time.sleep(3); atualizar_gerenciador()
                    return ao_clicar_substituir
                btn_sub.on_click(criar_evento_substituir(arq['caminho'], txt_link_sub, arq['nome']))
                display(linha)

atualizar_gerenciador()
abas = widgets.Tab(children=[box_downloader, out_gerenciador])
abas.set_title(0, '📥 Baixar Novos Arquivos')
abas.set_title(1, '📁 Gerenciar Meus Arquivos')
display(widgets.HTML("<h2>🎛️ Central de Modelos Civitai</h2>"), api_box, abas)

"""# Célula 5: O Play (Iniciando a Interface)
A última etapa, que fura o bloqueio visual do Colab e acende a placa A100.
"""

# Commented out IPython magic to ensure Python compatibility.
import os

print("🚀 ETAPA FINAL: INICIANDO O ESTÚDIO (ARQUITETURA OTIMIZADA)")
print("--------------------------------------------------")

forge_path = '/content/stable-diffusion-webui-forge'
args = os.environ.get('FORGE_ARGS', '--theme dark')
hardware = os.environ.get('HARDWARE_TYPE', 'GPU_LUXO')

print(f"⚙‣ Perfil: {hardware} | Args: {args}")
print("⏳ Gerando link público (gradio.live)...\n")

# %cd {forge_path}
# --skip-version-check impede que o Forge tente reinstalar o Numpy 2.x
!MPLBACKEND="agg" python3.10 launch.py {args} --share --enable-insecure-extension-access --skip-version-check --skip-python-version-check

import os

# Lista de arquivos de documentação para análise de requisitos
docs = [
    '/content/01-arquitetura.md',
    '/content/02-fluxo-de-execucao.md',
    '/content/04-hardware-otimizacao.md',
    '/content/05-modelos-e-pastas.md'
]

print('📖 Analisando Requisitos dos Documentos...')
for doc in docs:
    if os.path.exists(doc):
        with open(doc, 'r', encoding='utf-8') as f:
            print(f'\n--- {doc} ---')
            # Lendo as primeiras linhas para contextualizar a adaptação
            print(''.join(f.readlines()[:20]))
    else:
        print(f'⚠️ Arquivo {doc} não encontrado.')